fetch verse query
rogerrw/scriptural pull request #6
Opened 2024-12-13 00:19 UTC by cwong6854

2024-12-13 00:21 UTC, cwong6854 commented on app/api/mongodb/route.ts
> +        await client.connect();
need to fix this later, not hit client connect everytime endpoint is hit

2025-01-17 19:14 UTC, rogerrw requested changes

2025-01-17 19:14 UTC, rogerrw commented on app/page.tsx
>    async function getFetchedVerse() {
let's just call this fn `fetchVerse`

2025-01-17 19:14 UTC, rogerrw commented on lib/mongodb.ts
> +if (process.env.NODE_ENV === 'development') {
I think this makes sense but would you mind explaining why this if statement changed from 'production' to 'development' ?

2025-01-17 19:14 UTC, rogerrw commented on app/page.tsx
> +      var url = `/api/fetch_verse?book=${book}&chapter=${chapter}&verse=${verse}`;
use `let` instead of `var`

2025-01-17 19:14 UTC, rogerrw commented on app/api/fetch_verse/.gitignore
i think instead of excluding data.json here we should move this out to the main gitignore file.

2025-01-17 19:35 UTC, cwong6854 commented on lib/mongodb.ts
> +if (process.env.NODE_ENV === 'development') {
i reverted  from 'production' to 'development' because the vercel github repo with the mongodb example is also development. I'm assuming the logic is for development.

2025-01-17 19:41 UTC, rogerrw approved these changes

2025-01-17 21:27 UTC, merged